/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    val name: String = "Santi"
    var age = 16
    println("Hola me llamo $name tengo $age")
}
