/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    val name: String = "Santi" //constante definida con la siguiente sintaxis: val nombre_de_variable: <tipo_dato> = dato 
    var age = 16 //variable definida con la siguiente sintaxis: var nombre_de_variable = dato
    println("Hola me llamo $name tengo $age, pero este año cumplo ${age + 1}")

}
